version: "3.3"

services:
  # Database Postgres
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=sms
      - POSTGRES_USER=haris
      - POSTGRES_PASSWORD=haris123
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: postgres_db

  # Django Application
  django:
    container_name: docker-sms
    build:
      context: .
      dockerfile: Dockerfile
    image: app:django
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - db